name: terraform apply
on:
  push:
    branches: [ master ]
env:
  TF_VAR_AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  TF_VAR_AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
jobs:
  apply:
    name: terraform apply
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-1

      - name: terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.2
      - id: init
        run: terraform init
      - id: apply
        run: terraform apply -auto-approve -no-color
